#include <syslog.h>

#if 0
  openlog ("mylibrary", option, priority);
  syslog (LOG_INFO, "shared library has been invoked");
  closelog ();
#endif

#define DEBUG_MODE
#include "util_log.h"

int main(int argc, char **argv) {
// to file /var/log/syslog
// Apr 15 17:59:41 ubuntu test[8263]: This is a syslog test message generated by program './a.out'n 
//  openlog("test", LOG_CONS | LOG_PID, 0);
  OPEN_LOGG("athena_test");
//  syslog(LOG_INFO, "syslog test message generated by '%s'", argv[0]);
  LOGG_INFO("my words for this ", argv[0]);
// Apr 15 19:09:13 ubuntu athena [8681]: [8681][INFO] aaa./a.out
  closelog();

  return 0;
}

